services:
  backend:
    build: ./backend
    container_name: invoice-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI:-mongodb+srv://krishnayash955:kr1shn123@devops-project.alskdov.mongodb.net/?retryWrites=true&w=majority&appName=Devops-Project}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
    networks:
      - invoice-network

  frontend:
    build: ./frontend
    container_name: invoice-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - invoice-network

networks:
  invoice-network:
    driver: bridge